proyecto_cfca/urls.py
# -*- coding: utf-8 -*-
"""proyecto_cfca URL Configuration

The `urlpatterns` list routes URLs to views. For more information please see:
    https://docs.djangoproject.com/en/1.11/topics/http/urls/
Examples:
Function views
    1. Add an import:  from my_app import views
    2. Add a URL to urlpatterns:  url(r'^$', views.home, name='home')
Class-based views
    1. Add an import:  from other_app.views import Home
    2. Add a URL to urlpatterns:  url(r'^$', Home.as_view(), name='home')
Including another URLconf
    1. Import the include() function: from django.conf.urls import url, include
    2. Add a URL to urlpatterns:  url(r'^blog/', include('blog.urls'))
"""
from django.conf.urls import include, url
from django.contrib import admin
from django.conf.urls.static import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.contrib.auth import views as auth_views
from proyecto_cfca import settings
#vistas
from django.views.generic import TemplateView
from aprendizaje.views import signup

admin.site.site_header = 'Administración proyecto C.F.C.A'

urlpatterns = [
    url(r'', include('web.urls')),
    url(r'^login/$', auth_views.login, name='login'),
    url(r'^signup/$', signup, name='signup'),
    url(r'^paginas/', include('django.contrib.flatpages.urls')),
    url(r'^cursos/', include('aprendizaje.urls')),
    url(r'^encuestas/', include('encuestas.urls')),
    url(r'^admin/', admin.site.urls),
    url(r'^pages/', include('django.contrib.flatpages.urls')),
    url(r'^ckeditor/', include('ckeditor_uploader.urls')),
    url(r'^taggit_autosuggest/', include('taggit_autosuggest.urls')),
    url(r'^actividades/', include('actividades.urls')),
    url(r'^censo/', include('beneficiarios.urls')),
    url(r'^caps/', include('datosCaps.urls')),
    url(r'^lugar/', include('lugar.urls')),
    url(r'^app/v1/', include('appdirectorio.urls')),
    url(r'^api-auth/', include('rest_framework.urls', namespace='rest_framework')),
    url(r'^accounts/', include('allauth.urls')),
    url(r'^redes-sociales/', include('redes_sociales.urls')),
    #url(r'^webpush/', include('webpush.urls')),
    #url(r'^sw.js', TemplateView.as_view(template_name='sw.js', content_type='application/x-javascript')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL , document_root = settings.STATIC_ROOT )
    urlpatterns += static(settings.MEDIA_URL , document_root = settings.MEDIA_ROOT )
    import debug_toolbar
    urlpatterns.append(url(r'^__debug__/', include(debug_toolbar.urls)))

urlpatterns += staticfiles_urlpatterns()

web/urls.py
from django.conf.urls import url
from django.views.generic import TemplateView
from django.views.decorators.cache import cache_page

from . import views
from beneficiarios.views import (BeneficiarioHome, 
                                BeneficiarioInversion, 
                                BeneficiarioActividad, 
                                reporte_mejoras_perforacion)
from actividadgerencial.views import ActvidadesProgramatica, ResultadosView
from modulofinanciero.views import *
from peticiones.views import *
from participantes.views import *

urlpatterns = [
    url(r'^$', views.IndexView.as_view(), name="index"),
    url(r'^search/$', views.SearchResultsView.as_view(), name='search_results'),
    url(r'^lista-noticias/$', views.NewsListView.as_view(), name="list_news"),
    url(r'^lista-noticias-vidas/$', views.NewsListVidasView.as_view(), name="list_news-vidas"),
    url(r'^noticia/(?P<slug>[-\w]+)/$', views.NewsDetailView.as_view(), name="detail_news"),
    url(r'^documentos/$', views.DocumentListView.as_view(), name="list_documents"),
    #url(r'^galerias/$', views.GaleriaListView.as_view(), name="list_gallery"),
    url(r'^galerias/$', views.GaleriaListView.as_view(), name="list_gallery"),
    url(r'^videos/$', views.VideoListView.as_view(), name="list_videos"),
    url(r'^audios/$', TemplateView.as_view(template_name="web/audios_list.html")),
    url(r'^eventos/$', views.EventosListView.as_view(), name="list_eventos"),
    url(r'^eventos/(?P<slug>[-\w]+)/$', views.EventoDetailView.as_view(), name="detail_eventos"),
    url(r'^tags/(?P<slug>[-\w]+)/$', views.TagView.as_view(), name="tags_news"),
    url(r'^tematicas/(?P<tematicas>[-\w]+)/$', views.TematicaView.as_view(), name="tematicas_news"),
    url(r'^faq/$', TemplateView.as_view(template_name="web/faq.html")),
    url(r'^consulta/$', TemplateView.as_view(template_name="seguimiento/segimiento_consulta.html")),
    url(r'^beneficiario/$', BeneficiarioHome.as_view(), name='beneficiario'),
    url(r'^beneficiario-inversion/$', BeneficiarioInversion.as_view(), name='beneficiario-inversion'),
    # url(r'^beneficiario-actividad/$', BeneficiarioActividad.as_view(), name='beneficiario-actividad'),
    url(r'^resultado/$', ResultadosView, name="resultados"),
    url(r'^impacto/$', TemplateView.as_view(template_name="seguimiento/segimiento_impacto.html")),
    url(r'^financiero/$', financiero, name='modulo_financiero'),
    url(r'^actividades/$', ActvidadesProgramatica.as_view(), name="actividades-programaticas"),
    url(r'^perfilcaps/$', TemplateView.as_view(template_name="seguimiento/perfilcaps.html")),
    url(r'^peticiones/$', peticiones, name="peticiones"),
    url(r'^peticiones/make/$', save_peticiones, name="make_peticiones"),
    url(r'^peticiones/thank/$', TemplateView.as_view(template_name="peticiones/thank.html"), name="thank_peticiones"),
    url(r'^reporte-mejoras/(?P<year>\d+)/$', reporte_mejoras_perforacion, name="reporte"),
    url(r'^covid19-nicaragua/$', TemplateView.as_view(template_name="web/covid.html")),
    url(r'^filtro-encuestas/$', consultar_survey, name="consultar-survey"),
    url(r'^salida-filtro-encuestas/$', salidas_filtro_encuesta, name="salida-consultar-survey"),

]

peticiones/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
from django.utils.encoding import python_2_unicode_compatible
from django.utils import timezone as tz
from django.db import models

from lugar.models import Departamento, Municipio, Comunidad
from datosCaps.models import FichaCaps
# Create your models here.

@python_2_unicode_compatible
class Instituciones(models.Model):
    siglas = models.CharField(max_length=50)
    nombre_completo = models.CharField(max_length=250)

    def __str__(self):
        return self.siglas

    class Meta:
        verbose_name = 'Institución'
        verbose_name_plural = 'Instituciones'

@python_2_unicode_compatible
class TiposPeticiones(models.Model):
    titulo = models.CharField(max_length=250)

    def __str__(self):
        return self.titulo

    class Meta:
        verbose_name = 'Tipo Petición'
        verbose_name_plural = 'Tipos de peticiones'


@python_2_unicode_compatible
class Contactos(models.Model):
    nombre = models.CharField(max_length=250)
    correo = models.EmailField()
    institucion_pertenece = models.ForeignKey(Instituciones)

    def __str__(self):
        return "%s - %s" % (self.nombre, self.institucion_pertenece)

    class Meta:
        verbose_name = 'Contacto'
        verbose_name_plural = 'Contactos'

CHOICE_GENERO = (('hombre','Hombre'),('mujer','Mujer'))
CHOICE_FORMATO = ((1,'Escrito'),(2,'Whatsapp'),(3,'Correo Electronico'),(4,'Facebook'))
CHOICE_TIPO_ACCION = ((1,'Petición'),(2,'Consulta'))

@python_2_unicode_compatible
class Peticion(models.Model):
    fecha = models.DateTimeField(default=tz.now)
    caps = models.ForeignKey(FichaCaps)
    sexo = models.CharField('Sexo del que hace la petición',choices=CHOICE_GENERO,
        max_length=10, null=True, blank=True)
    formato = models.IntegerField(choices=CHOICE_FORMATO, null=True, blank=True)
    tipo_accion = models.IntegerField(choices=CHOICE_TIPO_ACCION, null=True, blank=True)
    solicitud_a = models.ManyToManyField(Instituciones, blank=True)
    tipo_peticion = models.ForeignKey(TiposPeticiones, null=True, blank=True)
    # institucion = models.ForeignKey(Instituciones, verbose_name="Institución que dirige la petición",
    #     null=True, blank=True)
    descripcion = models.TextField("Descripción de la petición")
    

    def __str__(self):
        return "%s -- FECHA: %s" % (self.caps.nombre_caps, self.fecha.strftime("%d %B %Y"))

    class Meta:
        verbose_name = 'Petición'
        verbose_name_plural = 'Peticiones'
        ordering = ('-fecha',)

CHOICE_TIPO_RESPUESTA = ((1,'Resuelta'),(2,'En proceso'))

class RespuestaPeticion(models.Model):
    peticion = models.ForeignKey(Peticion)
    fecha = models.DateField(null=True, blank=True)
    tipo_resolucion = models.IntegerField(choices=CHOICE_TIPO_RESPUESTA, 
                                          null=True, blank=True)
    #resuelta = models.BooleanField(default=False)
    respuesta = models.TextField('Respuesta a la peticion')
    por_escrito = models.BooleanField()
    por_verbal = models.BooleanField()
    subir_archivo = models.FileField(upload_to='adjuntosPeticiones/', null=True, blank=True)
    #sin_respuesta = models.BooleanField(editable=False)


    def __str__(self):
        return "%s" % self.peticion

    class Meta:
        verbose_name = 'Respuesta a la petición'
        verbose_name_plural = 'Respuestas a las peticiones'

peticiones/forms.py
from django import forms
from django.utils import timezone as tz
from .models import *
from dal import autocomplete
from ckeditor_uploader.widgets import CKEditorUploadingWidget

class PeticionForm(forms.ModelForm):
    # def __init__(self, *args, **kwargs):
    #     super(PeticionForm, self).__init__(*args, **kwargs)
    #     self.fields['fecha'] = forms.CharField(required=True)
    #     self.fields['caps'] = forms.ModelChoiceField(queryset=FichaCaps.objects.select_related('departamento','municipio').prefetch_related('comunidad'), required=True)
    #     self.fields['sexo'] = forms.ChoiceField(choices=CHOICE_GENERO,required=True)
    #     self.fields['tipo_accion'] = forms.ChoiceField(choices=CHOICE_TIPO_ACCION,required=True)
    #     self.fields['institucion'] = forms.ModelChoiceField(queryset=Instituciones.objects.all(),required=True)
    #     self.fields['descripcion'] = forms.CharField(required=True, widget=forms.Textarea)
    #     self.fields['tipo_peticion'] = forms.ModelChoiceField(queryset=TiposPeticiones.objects.all(),required=True)
      
    class Meta:
        model = Peticion
        fields = '__all__'

class RespuestaPeticionesForm(forms.ModelForm):
    respuesta = forms.CharField(widget=CKEditorUploadingWidget())
    class Meta:
        model = RespuestaPeticion
        fields = '__all__'
        widgets = {
            'peticion': autocomplete.ModelSelect2(url='peticion-autocomplete', attrs={'data-language': 'es'}),   
        }

peticiones/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.shortcuts import render, redirect
from django.utils import timezone
from .models import *
from .forms import PeticionForm
import datetime
from dal import autocomplete

# Create your views here.
class PeticionRespuestaAutocomplete(autocomplete.Select2QuerySetView):
    def get_queryset(self):
        qs = Peticion.objects.all()
        if self.q:
            qs = qs.filter(caps__nombre_caps__istartswith=self.q)

        return qs

def peticiones(request, template = "seguimiento/peticiones.html"):
    total_peticiones = Peticion.objects.count()
    peticiones_resueltas = RespuestaPeticion.objects.filter(tipo_resolucion=1).count()
    peticiones_pendientes = total_peticiones - peticiones_resueltas

    tabla = Peticion.objects.select_related('tipo_peticion').prefetch_related('caps','solicitud_a').order_by('-fecha')
    # .values_list('tipo_peticion__titulo','fecha','sexo','caps__nombre_caps',
    #              'solicitud_a__siglas','respuestapeticion__fecha',
    #              'respuestapeticion__resuelta','descripcion','id').distinct()

    map_peticiones = Peticion.objects.filter(caps__latitud__gt=0).values_list('caps__latitud',
                                                                'caps__longitud',
                                                                'caps__nombre_caps',
                                                                'caps__direccion',
                                                                'caps__municipio__nombre',
                                                                'caps__id')

    grafo_municipios = {}
    for x in Municipio.objects.all():
        conteo = tabla.filter(caps__municipio_id = x.id).count()
        if conteo > 0:
            grafo_municipios[x.nombre] = conteo
    
    sexo_peticion = {}
    for x in CHOICE_GENERO:
        conteo = Peticion.objects.filter(sexo = x[0]).count()
        sexo_peticion[x[1]] = conteo

    formato_peticion = {}
    for x in CHOICE_FORMATO:
        conteo = Peticion.objects.filter(formato = x[0]).count()
        formato_peticion[x[1]] = conteo

    grafo_peticion = {}
    for x in TiposPeticiones.objects.all():
        conteo = Peticion.objects.filter(tipo_peticion = x).count()
        porcentaje = round(( conteo / total_peticiones ) * 100, 2)
        grafo_peticion[x.titulo] = (conteo, porcentaje)

    return render(request,template,locals())

def save_peticiones(request, template="peticiones/save_peticiones.html"):
    if request.method == 'POST':
        form = PeticionForm(request.POST)
        if form.is_valid():
            form.save() 
            return redirect('/peticiones/thank/')
        else:
            print("Hubo error no se grabo nada!")
    else:
        form = PeticionForm()
    return render(request, template, locals())

templates/peticiones/save_peticiones.html
{% load widget_tweaks static %}
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-wEmeIV1mKuiNpC+IOBjI7aAzPcEZeedi5yW5f2yOq55WWLwNGmvvx4Um1vskeMj0" crossorigin="anonymous">
    <link href="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/css/select2.min.css" rel="stylesheet" />

    <title>CFCA - Hacer una Petición</title>
  </head>
  <body>
    <div class="container">
      <div class="row justify-content-md-center">
        <div class="col">
          <form action="." method="POST">
            {% csrf_token %}
            <div class="mb-3">
              {% render_field form.fecha class+="form-control" %}
            </div>
            <div class="mb-3">
              <label for="InputCaps" class="form-label">Escoja su CAPS</label>
              {% render_field form.caps class+="form-select" %}
              <div id="emailHelp" class="form-text">Seleccionar el nombre de su CAPS</div>
            </div>
            <div class="mb-3">
              <label for="sexo" class="form-label">Seleccione su sexo</label>
              {% render_field form.sexo class+="form-select" %}
            </div>
            <div class="mb-3">
              <label for="accion" class="form-label">Tipo de acción</label>
              {% render_field form.tipo_accion class+="form-select" %}
            </div>
            <div class="mb-3">
              <label for="institucion" class="form-label">Institución que dirige la petición</label>
              {% render_field form.solicitud_a class+="form-control" %}
            </div>
            <div class="mb-3">
              <label for="tipo_peticion" class="form-label">Tipo de petición</label>
              {% render_field form.tipo_peticion class+="form-select" %}
            </div>
            <div class="mb-3">
              <label for="descripcion" class="form-label">Describa su petición</label>
              {% render_field form.descripcion class+="form-control" %}
            </div>
            <button type="submit" class="btn btn-primary">Enviar Petición</button>
          </form>
        </div>
      </div>
    </div>

    
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-p34f1UUtsS3wqzfto5wAAmdvj+osOnFyQFpp4Ua3gs/ZVWx6oOypYoCJhGGScy+8" crossorigin="anonymous"></script>
    <script
  src="https://code.jquery.com/jquery-3.6.0.min.js"
  integrity="sha256-/xUj+3OJU5yExlq6GSYGSHk7tPXikynS7ogEvDej/m4="
  crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/js/select2.min.js"></script>
    <script>
    document.querySelector('#id_fecha').style.display = 'none';
    $(document).ready(function() {
      $('#id_solicitud_a').select2();
    });

    </script>
  </body>
</html>

templates/peticiones/thank.html
{% load widget_tweaks static %}
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-wEmeIV1mKuiNpC+IOBjI7aAzPcEZeedi5yW5f2yOq55WWLwNGmvvx4Um1vskeMj0" crossorigin="anonymous">

    <title>CFCA - Hacer una Petición</title>
  </head>
  <body>
    <div class="container">
      <div class="row justify-content-md-center">
        <div class="col">
          <div class="card">
            <div class="card-body">
              <h3 class="text-center">Gracias, su petición fue enviada con exito!</h3>
            </div>
          </div>
        </div>
      </div>
    </div>

    
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-p34f1UUtsS3wqzfto5wAAmdvj+osOnFyQFpp4Ua3gs/ZVWx6oOypYoCJhGGScy+8" crossorigin="anonymous"></script>
    
  </body>
</html>