proyecto_cfca/urls.py
# -*- coding: utf-8 -*-
"""proyecto_cfca URL Configuration

The `urlpatterns` list routes URLs to views. For more information please see:
    https://docs.djangoproject.com/en/1.11/topics/http/urls/
Examples:
Function views
    1. Add an import:  from my_app import views
    2. Add a URL to urlpatterns:  url(r'^$', views.home, name='home')
Class-based views
    1. Add an import:  from other_app.views import Home
    2. Add a URL to urlpatterns:  url(r'^$', Home.as_view(), name='home')
Including another URLconf
    1. Import the include() function: from django.conf.urls import url, include
    2. Add a URL to urlpatterns:  url(r'^blog/', include('blog.urls'))
"""
from django.conf.urls import include, url
from django.contrib import admin
from django.conf.urls.static import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.contrib.auth import views as auth_views
from proyecto_cfca import settings
#vistas
from django.views.generic import TemplateView
from aprendizaje.views import signup

admin.site.site_header = 'Administración proyecto C.F.C.A'

urlpatterns = [
    url(r'', include('web.urls')),
    url(r'^login/$', auth_views.login, name='login'),
    url(r'^signup/$', signup, name='signup'),
    url(r'^paginas/', include('django.contrib.flatpages.urls')),
    url(r'^cursos/', include('aprendizaje.urls')),
    url(r'^encuestas/', include('encuestas.urls')),
    url(r'^admin/', admin.site.urls),
    url(r'^pages/', include('django.contrib.flatpages.urls')),
    url(r'^ckeditor/', include('ckeditor_uploader.urls')),
    url(r'^taggit_autosuggest/', include('taggit_autosuggest.urls')),
    url(r'^actividades/', include('actividades.urls')),
    url(r'^censo/', include('beneficiarios.urls')),
    url(r'^caps/', include('datosCaps.urls')),
    url(r'^lugar/', include('lugar.urls')),
    url(r'^app/v1/', include('appdirectorio.urls')),
    url(r'^api-auth/', include('rest_framework.urls', namespace='rest_framework')),
    url(r'^accounts/', include('allauth.urls')),
    url(r'^redes-sociales/', include('redes_sociales.urls')),
    #url(r'^webpush/', include('webpush.urls')),
    #url(r'^sw.js', TemplateView.as_view(template_name='sw.js', content_type='application/x-javascript')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL , document_root = settings.STATIC_ROOT )
    urlpatterns += static(settings.MEDIA_URL , document_root = settings.MEDIA_ROOT )
    import debug_toolbar
    urlpatterns.append(url(r'^__debug__/', include(debug_toolbar.urls)))

urlpatterns += staticfiles_urlpatterns()

web/urls.py
from django.conf.urls import url
from django.views.generic import TemplateView
from django.views.decorators.cache import cache_page

from . import views
from beneficiarios.views import (BeneficiarioHome, 
                                BeneficiarioInversion, 
                                BeneficiarioActividad, 
                                reporte_mejoras_perforacion)
from actividadgerencial.views import ActvidadesProgramatica, ResultadosView
from modulofinanciero.views import *
from peticiones.views import *
from participantes.views import *

urlpatterns = [
    url(r'^$', views.IndexView.as_view(), name="index"),
    url(r'^search/$', views.SearchResultsView.as_view(), name='search_results'),
    url(r'^lista-noticias/$', views.NewsListView.as_view(), name="list_news"),
    url(r'^lista-noticias-vidas/$', views.NewsListVidasView.as_view(), name="list_news-vidas"),
    url(r'^noticia/(?P<slug>[-\w]+)/$', views.NewsDetailView.as_view(), name="detail_news"),
    url(r'^documentos/$', views.DocumentListView.as_view(), name="list_documents"),
    #url(r'^galerias/$', views.GaleriaListView.as_view(), name="list_gallery"),
    url(r'^galerias/$', views.GaleriaListView.as_view(), name="list_gallery"),
    url(r'^videos/$', views.VideoListView.as_view(), name="list_videos"),
    url(r'^audios/$', TemplateView.as_view(template_name="web/audios_list.html")),
    url(r'^eventos/$', views.EventosListView.as_view(), name="list_eventos"),
    url(r'^eventos/(?P<slug>[-\w]+)/$', views.EventoDetailView.as_view(), name="detail_eventos"),
    url(r'^tags/(?P<slug>[-\w]+)/$', views.TagView.as_view(), name="tags_news"),
    url(r'^tematicas/(?P<tematicas>[-\w]+)/$', views.TematicaView.as_view(), name="tematicas_news"),
    url(r'^faq/$', TemplateView.as_view(template_name="web/faq.html")),
    url(r'^consulta/$', TemplateView.as_view(template_name="seguimiento/segimiento_consulta.html")),
    url(r'^beneficiario/$', BeneficiarioHome.as_view(), name='beneficiario'),
    url(r'^beneficiario-inversion/$', BeneficiarioInversion.as_view(), name='beneficiario-inversion'),
    # url(r'^beneficiario-actividad/$', BeneficiarioActividad.as_view(), name='beneficiario-actividad'),
    url(r'^resultado/$', ResultadosView, name="resultados"),
    url(r'^impacto/$', TemplateView.as_view(template_name="seguimiento/segimiento_impacto.html")),
    url(r'^financiero/$', financiero, name='modulo_financiero'),
    url(r'^actividades/$', ActvidadesProgramatica.as_view(), name="actividades-programaticas"),
    url(r'^perfilcaps/$', TemplateView.as_view(template_name="seguimiento/perfilcaps.html")),
    url(r'^peticiones/$', peticiones, name="peticiones"),
    url(r'^peticiones/make/$', save_peticiones, name="make_peticiones"),
    url(r'^peticiones/thank/$', TemplateView.as_view(template_name="peticiones/thank.html"), name="thank_peticiones"),
    url(r'^reporte-mejoras/(?P<year>\d+)/$', reporte_mejoras_perforacion, name="reporte"),
    url(r'^covid19-nicaragua/$', TemplateView.as_view(template_name="web/covid.html")),
    url(r'^filtro-encuestas/$', consultar_survey, name="consultar-survey"),
    url(r'^salida-filtro-encuestas/$', salidas_filtro_encuesta, name="salida-consultar-survey"),

]

models.py
# This is an auto-generated Django model module created by ogrinspect.
from django.contrib.gis.db import models

class Beneficiarios(models.Model):
    start = models.CharField(max_length=0)
    end = models.CharField(max_length=0)
    username = models.CharField(max_length=0)
    deviceid = models.CharField(max_length=0)
    phonenumber = models.CharField(max_length=0)
    nombre y apellido = models.CharField(max_length=0)
    es jefe de familia? = models.CharField(max_length=0)
    comunidad = models.CharField(max_length=0)
    municipio = models.CharField(max_length=0)
    departamento = models.CharField(max_length=0)
    sexo = models.CharField(max_length=0)
    fecha de nacimiento = models.CharField(max_length=0)
    existe caps = models.CharField(max_length=0)
    nombre del caps = models.CharField(max_length=0)
    cargo dentro del caps = models.CharField(max_length=0)
    que compañia es? = models.CharField(max_length=0)
    su número telefonico = models.CharField(max_length=0)
    localizacion = models.CharField(max_length=0)
    _localizacion_latitude = models.CharField(max_length=0)
    _localizacion_longitude = models.CharField(max_length=0)
    _localizacion_altitude = models.CharField(max_length=0)
    _localizacion_precision = models.CharField(max_length=0)
    jefe_familia = models.CharField(max_length=0)
    nombre_caps = models.CharField(max_length=0)
    _id = models.CharField(max_length=0)
    _uuid = models.CharField(max_length=0)
    _submission_time = models.CharField(max_length=0)
    _validation_status = models.CharField(max_length=0)
    _index = models.CharField(max_length=0)
    geom = models.None(srid=-1)

encuestas/forms.py
# -*- coding: utf-8 -*-
from django import forms
from django.forms import models
from django.utils.safestring import mark_safe

from lugar.models import Municipio, Comunidad
from datosCaps.models import FichaCaps
from encuestas.models import Question, Category, Survey, Response, AnswerText, AnswerRadio, AnswerSelect, AnswerInteger, AnswerSelectMultiple

import uuid

# blatantly stolen from
# http://stackoverflow.com/questions/5935546/align-radio-buttons-horizontally-in-django-forms?rq=1
#class HorizontalRadioRenderer(forms.RadioSelect.renderer):
#  def render(self):
#    return mark_safe(u'\n'.join([u'%s\n' % w for w in self]))
CHOICES_SEXO = (
                (1, 'Hombre'),
                (2, 'Mujer'),
    )

CHOICES_EDAD_RANGOS = (
                (1, '16 - 22'),
                (2, '23 - 29'),
                (3, '30 - 36'),
                (4, '37 - 43'),
                (5, '44 - 49'),
                (6, '50 - 56'),
                (7, '57 en adelante'),
    )

class ResponseForm(models.ModelForm):
    sexo = forms.ChoiceField(
        required=False,
        widget=forms.RadioSelect,
        choices=CHOICES_SEXO)
    rango_edad = forms.ChoiceField(
        required=False,
        widget=forms.RadioSelect,
        choices=CHOICES_EDAD_RANGOS)
    class Meta:
        model = Response
        fields = ('interviewee','municipio','comunidad','caps','sexo','rango_edad')

    def __init__(self, *args, **kwargs):
        # espera que un objeto de encuesta sea aprobado inicialmente
        survey = kwargs.pop('survey')
        self.survey = survey
        super(ResponseForm, self).__init__(*args, **kwargs)
        self.uuid = random_uuid = uuid.uuid4().hex

        # agregue un campo para cada pregunta de la encuesta, correspondiente al tipo de pregunta
        # según corresponda.
        data = kwargs.get('data')
        for q in survey.questions().order_by('order'):
            if q.question_type == Question.TEXT:
                self.fields["question_%d" % q.pk] = forms.CharField(label=q.text,
                    widget=forms.Textarea)
            elif q.question_type == Question.RADIO:
                question_choices = q.get_choices()
                self.fields["question_%d" % q.pk] = forms.ChoiceField(label=q.text,
                    widget=forms.RadioSelect(),
                    choices = question_choices)
            elif q.question_type == Question.SELECT:
                question_choices = q.get_choices()
                # agregue una opción vacía en la parte superior para que el usuario tenga que
                # seleccionar explícitamente una de las opciones
                question_choices = tuple([('', '-------------')]) + question_choices
                self.fields["question_%d" % q.pk] = forms.ChoiceField(label=q.text,
                    widget=forms.Select, choices = question_choices)
            elif q.question_type == Question.SELECT_MULTIPLE:
                question_choices = q.get_choices()
                self.fields["question_%d" % q.pk] = forms.MultipleChoiceField(label=q.text,
                    widget=forms.CheckboxSelectMultiple, choices = question_choices)
            elif q.question_type == Question.INTEGER:
                self.fields["question_%d" % q.pk] = forms.IntegerField(label=q.text)

            # si el campo es obligatorio, proporciónalo con una clase CSS correspondiente.
            if q.required:
                self.fields["question_%d" % q.pk].required = True
                self.fields["question_%d" % q.pk].widget.attrs["class"] = "required"
            else:
                self.fields["question_%d" % q.pk].required = False

            # agregue la categoría como una clase css, y agréguela como un atributo de datos
            # también (esto se usa en la plantilla para permitir ordenar las preguntas por categoría)
            if q.category:
                classes = self.fields["question_%d" % q.pk].widget.attrs.get("class")
                if classes:
                    self.fields["question_%d" % q.pk].widget.attrs["class"] = classes + (" cat_%s" % q.category.name)
                else:
                    self.fields["question_%d" % q.pk].widget.attrs["class"] = (" cat_%s" % q.category.name)
                self.fields["question_%d" % q.pk].widget.attrs["category"] = q.category.name


            # inicialice el campo de formulario con los valores de una solicitud POST, si corresponde.
            if data:
                self.fields["question_%d" % q.pk].initial = data.get('question_%d' % q.pk)

    def save(self, commit=True):
        # guardar el objeto de respuesta
        response = super(ResponseForm, self).save(commit=False)
        response.survey = self.survey
        response.interview_uuid = self.uuid
        response.save()

        # crear un objeto de respuesta para cada pregunta y asociarlo con esta
        # respuesta.
        for field_name, field_value in self.cleaned_data.items():
            if field_name.startswith("question_"):
                # advertencia: esta forma de extraer la identificación es muy frágil y
                # completamente dependiente de la forma en que el question_id está codificado en el
                # nombre de campo en el método __init__ de esta clase de formulario.
                q_id = int(field_name.split("_")[1])
                q = Question.objects.get(pk=q_id)

                if q.question_type == Question.TEXT:
                    a = AnswerText(question = q)
                    a.body = field_value
                elif q.question_type == Question.RADIO:
                    a = AnswerRadio(question = q)
                    a.body = field_value
                elif q.question_type == Question.SELECT:
                    a = AnswerSelect(question = q)
                    a.body = field_value
                elif q.question_type == Question.SELECT_MULTIPLE:
                    a = AnswerSelectMultiple(question = q)
                    a.body = field_value
                elif q.question_type == Question.INTEGER:
                    a = AnswerInteger(question = q)
                    a.body = field_value
                #print "creando una respuesta para la pregunta %d de tipo %s" % (q_id, a.question.question_type)
                #print a.question.text
                #print 'valor de respuesta:'
                #print field_value
                a.response = response
                a.save()
        return response



CHOICES_SEXO2 = (
                ('', '------'),
                (1, 'Hombre'),
                (2, 'Mujer'),
    )

CHOICES_EDAD_RANGOS2 = (
                ('', '--------'),
                (1, '16 - 22'),
                (2, '23 - 29'),
                (3, '30 - 36'),
                (4, '37 - 43'),
                (5, '44 - 49'),
                (6, '50 - 56'),
                (7, '57 en adelante'),
    )

class ConsultaForm(forms.Form):
    def __init__(self, *args, **kwargs):
        super(ConsultaForm, self).__init__(*args, **kwargs)
        self.fields['fecha_inicial'].widget.attrs.update({'class': 'form-control ',
                                                   'data-placeholder':'Fecha inicial', 'tabindex':'-1','area-hidden': 'true'})
        self.fields['fecha_final'].widget.attrs.update({'class': 'form-control ',
                                                   'data-placeholder':'Fecha final', 'tabindex':'-1','area-hidden': 'true'})
        self.fields['municipio'].widget.attrs.update({'class': 'select2 select2-container select2-container--default select2-container--above'})
        self.fields['comunidad'].widget.attrs.update({'class': 'select2 select2-container select2-container--default select2-container--above'})
        self.fields['caps'].widget.attrs.update({'class': 'select2 select2-container select2-container--default select2-container--above'})
        self.fields['sexo'].widget.attrs.update({'class': 'select2 select2-container select2-container--default select2-container--above'})
        self.fields['rango_edad'].widget.attrs.update({'class': 'select2 select2-container select2-container--default select2-container--above'})

        # if 'pais' in self.data:
        #     try:
        #         pais_id = int(self.data.get('pais'))
        #         self.fields['departamento'].queryset = Departamento.objects.filter(pais_id=pais_id).order_by('nombre')
        #     except (ValueError, TypeError):
        #         pass  # invalid input from the client; ignore and fallback to empty City queryset

        if 'comunidad' in self.data:
            try:
                municipio_id = int(self.data.get('municipio'))
                self.fields['comunidad'].queryset = Comunidad.objects.filter(municipio_id=municipio_id).order_by('nombre')
            except (ValueError, TypeError):
                pass  # invalid input from the client; ignore and fallback to empty Comunidad queryset

        if 'caps' in self.data:
            try:
                comunidad_id = int(self.data.get('comunidad'))
                self.fields['caps'].queryset = FichaCaps.objects.filter(comunidad=comunidad_id).order_by('nombre_caps')
            except (ValueError, TypeError):
                pass  # invalid input form the client

    fecha_inicial = forms.CharField(widget=forms.DateInput(), required=True)
    fecha_final = forms.CharField(widget=forms.DateInput(), required=True)
    sexo = forms.ChoiceField(choices=CHOICES_SEXO2, required=False)
    rango_edad = forms.ChoiceField(choices=CHOICES_EDAD_RANGOS2, required=False, label='Rango de edad')
    municipio = forms.ModelChoiceField(queryset=Municipio.objects.all(), required=False)
    comunidad = forms.ModelChoiceField(queryset=Comunidad.objects.none(), required=False)
    caps = forms.ModelChoiceField(queryset=FichaCaps.objects.none(), required=False)

templates/filtros/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="shortcut icon" type="image/png" href="{% static 'img/logos/favicon.ico' %}"/>
    <title>Filtros</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.5.1.js" integrity="sha256-QWo7LDvxbWT2tbbQ97B53yJnYU3WhH/C8ycbRAkjPDc=" crossorigin="anonymous"></script>
    {% block extra_css %}
        
    {% endblock extra_css %}
</head>
<body>

<main role="main">

{% block contenido %}{% endblock contenido %}

</main>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
{% block extra_js %}
{% endblock extra_js %}
</body>
</html>

templates/filtros/consultar.html
{% extends "filtros/base.html" %}

{% block extra_css %}
<link href="https://cdn.jsdelivr.net/npm/select2@4.1.0-beta.1/dist/css/select2.min.css" rel="stylesheet" />
<script src="https://cdn.jsdelivr.net/npm/select2@4.1.0-beta.1/dist/js/select2.min.js"></script>
<link rel="stylesheet" href="/static/bootstrap-datepicker/css/bootstrap-datepicker3.min.css">
<link rel="stylesheet" href="/static/bootstrap-datepicker/css/bootstrap-datepicker3.standalone.min.css">
<style>
 #id_actividad_principal {
    width: 100px;
 }
 #id_departamento {
    width: 222px !important;
 }
 .select2-container--default .select2-selection--single {
    background-color: #fff;
    border: 1px solid #aaa;
    border-radius: 4px;
    height: 40px !important;
}
.select2-container .select2-selection--single {
    box-sizing: border-box;
    cursor: pointer;
    display: block;
    height: 40px !important;
    user-select: none;
    -webkit-user-select: none;
}
</style>  
{% endblock extra_css %}

{% block contenido %}
<section class="jumbotron text-center">
    <div class="container">
      <div class="row">
        <div class="col-md-12 col-xs-12 col-sm-12">
          <div class="card shadow mb-4">
            <div class="card-header py-3">
              <h6 class="m-0 font-weight-bold text-primary">CONSULTAR FILTROS</h6>
            </div>
            <div class="card-body">
            <form action="." method="POST" autocomplete="off">
                {% csrf_token %}
                {{ form.media }}
                {% for hidden_field in form.hidden_fields %}
                {{ hidden_field }}
                {% endfor %}
                <div class="form-row">
                    <div class="form-group col-md-4">
                        <label for="fecha">Fecha inicial</label>
                        {{form.fecha_inicial}}
                    </div>
                    <div class="form-group col-md-4">
                        <label for="fecha">Fecha final</label>
                        {{form.fecha_final}}
                    </div>
                </div>

               <div class="form-row">
                    <div class="form-group col-md-4">
                        <label for="departamento">Departamento</label>
                        {{form.departamento}}
                    </div>
                    <div class="form-group col-md-4">
                        <label for="municipio">Municipio</label>
                        {{form.municipio}}
                    </div>
                </div>

                <div class="form-row">
                    <div class="form-group col-md-4">
                        <label for="comunidad">Comunidad</label>
                        {{form.comunidad}}
                    </div>
                    <div class="form-group col-md-4">
                        <label for="tema">Tema</label>
                        {{form.tema}}
                    </div>
                </div>
            
               <div class="form-row">
                    <div class="form-group col-md-4">
                        <label for="actividad_principal">Actividad principal</label>
                        {{form.actividad_principal}}
                    </div>
                    <div class="form-group col-md-4">
                        <label for="tipo_actividad">Tipo actividad</label>
                        {{form.tipo_actividad}}
                    </div>
                </div>
         
                <div class="form-row">
                    <div class="form-group col-md-4">
                        <label for="modulos">Modulos</label>
                        {{form.modulos}}
                    </div>
                </div>

                <div class="d-flex justify-content-center">
                    <input type="submit" value="Consultar" id="boton" class="btn btn-success center-block" />
                </div>
            </form>
        </div> <!-- card body -->
        </div> <!-- card -->
        </div> <!-- col-12 -->
      </div> <!-- row -->
    </div> <!-- container -->
</section>
<div class="py-5 bg-light">
    <div class="container">

        <div class="row">
            
        <div class="col-md-12">
          <div class="card mb-4 box-shadow">
            <div class="card-body">
              
              <div class="d-flex justify-content-between align-items-center">
                <p>
                {%if centinela == 1 %}
                    <a target="_blank" href="{% url 'salida_generica' %}" class="btn btn-primary my-2">Salida por Caps</a>
                    <a target="_blank" href="{% url 'salida_miembros' %}" class="btn btn-primary my-2">Salida Miembros</a>
                    <a target="_blank" href="{% url 'salida_inversiones' %}" class="btn btn-primary my-2">tabla inversiones</a>
                    <a target="_blank" href="{% url 'salida_beneficiario' %}" class="btn btn-primary my-2">Salida beneficiario</a>
                    <a target="_blank" href="{% url 'beneficiario_inversion' %}" class="btn btn-primary my-2">Beneficiario inversion</a>
                {% endif %}
                </p>
              </div>

            </div>
          </div>
            </div>

        </div>
    </div>
</div>
{% endblock contenido %}
{% block extra_js %}
<script src="/static/bootstrap-datepicker/js/bootstrap-datepicker.min.js"></script>
<script src="/static/bootstrap-datepicker/locales/bootstrap-datepicker.es.min.js"></script>
<script type="text/javascript">
    
$('#id_fecha_inicial').datepicker({
    format: "yyyy-mm-dd",
    language: "es",
    autoclose: true
});
$('#id_fecha_final').datepicker({
    format: "yyyy-mm-dd",
    language: "es",
    autoclose: true
});

</script>
<script>
$(document).ready(function() {
    $('#id_departamento').select2({
        placeholder: "Seleccione departamento",
        allowClear: true
    });
    $('#id_tipo_actividad').select2({
        placeholder: "Tipos de actividad",
        allowClear: true
    });
    $('#id_modulos').select2({
        placeholder: "Seleccione modulos",
        allowClear: true
    });

}); 
</script> 
{% endblock extra_js %}

templates/filtros/filtro_censo.html
{% extends "filtros/base.html" %}

{% block extra_css %}
<link rel="stylesheet" href="https://cdn.datatables.net/1.10.22/css/jquery.dataTables.min.css">
<link rel="stylesheet" href="https://cdn.datatables.net/buttons/1.6.4/css/buttons.dataTables.min.css">
{% endblock extra_css %}

{% block contenido %}

<section class="jumbotron text-center">
    <div class="container">
      <div class="row">
        <div class="col-md-12 col-xs-12 col-sm-12">
          <div class="card shadow mb-4">
            <div class="card-header py-3">
              <h6 class="m-0 font-weight-bold text-primary">FILTROS REALIZADOS</h6>
            </div>
            <div class="card-body">
            {% include "filtros/filtros.html" %}
            </div> <!-- card body {{request.session.items}} -->
          </div> <!-- card -->
        </div> <!-- col-12 -->
      </div> <!-- row -->
    </div> <!-- container -->
</section>
<div class="py-5 bg-light">
    <div class="container">

        <div class="row">
            
        <div class="col-md-12">
          <div class="card mb-4 box-shadow">
            <div class="card-body">
              <p>Total de personas: <span>{{conteo}}</span> </p>
              <div class="d-flex justify-content-between align-items-center">
                <p>
        <table id="example" class="display" style="width:100%">
        <thead>
            <tr>
                <th>Nombre apellido</th>
                <th>Jefe familia</th>
                <th>Municipio</th>
                <th>Comunidad</th>
                <th>Sexo</th>
                <th>Fecha nacimiento</th>
                <th>Caps al que pertenece</th>
                <th>Cargo caps</th>
                <th>Discapasidad</th>
            </tr>
        </thead>
        <tbody>
        {% for obj in filtro %}
        <tr>
            <td>{{obj.nombre_apellido}}</td>
            <td>{{obj.get_jefe_familia_display}}</td>
            <td>{{obj.municipio.nombre}}</td>
            <td>{{obj.comunidad.nombre}}</td>
            <td>{{obj.get_sexo_display}}</td>
            <td>{{obj.fecha_nacimiento}}</td>
            <td>{{obj.nombre_caps|default:"N/R"}}</td>
            <td>{{obj.cargo_caps|default:"N/R"}}</td>
            <td>{{obj.get_discapasidad_display|default:"N/R"}}</td>
        </tr>
        {% endfor %} 
        </tbody>
        <tfoot>
            <tr>
                <th>Nombre apellido</th>
                <th>Jefe familia</th>
                <th>Municipio</th>
                <th>Comunidad</th>
                <th>Sexo</th>
                <th>Fecha nacimiento</th>
                <th>Caps al que pertenece</th>
                <th>Cargo caps</th>
                <th>Discapasidad</th>
            </tr>
        </tfoot>
    </table>
                </p>
              </div>

            </div>
          </div>
            </div>

        </div>
    </div>
</div>
{% endblock contenido %}

{% block extra_js %}
<script src="https://code.jquery.com/jquery-3.5.1.js"></script>
<script src="https://cdn.datatables.net/1.10.22/js/jquery.dataTables.min.js"></script>
<script src="https://cdn.datatables.net/buttons/1.6.4/js/dataTables.buttons.min.js"></script>
<script src="https://cdn.datatables.net/buttons/1.6.4/js/buttons.flash.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/jszip/3.1.3/jszip.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/pdfmake/0.1.53/pdfmake.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/pdfmake/0.1.53/vfs_fonts.js"></script>
<script src="https://cdn.datatables.net/buttons/1.6.4/js/buttons.html5.min.js"></script>
<script src="https://cdn.datatables.net/buttons/1.6.4/js/buttons.print.min.js"></script>
<script>
$(document).ready(function() {
    $('#example').DataTable( {
        dom: 'Bfrtip',
        buttons: [
           'excel'
        ],
        "pageLength": 100,
        "paging":   true,
        "ordering": true,
        "info":     true
    } );
} );
</script> 
{% endblock extra_js %}