encuestas/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^$', views.Index, name='home'),
    url(r'^survey/(?P<id>\d+)/$', views.SurveyDetail, name='survey_detail'),
    url(r'^confirm/(?P<uuid>\w+)/$', views.confirm, name='confirmation'),
    url(r'^analisis/survey/(?P<id>\d+)/$', views.stadistic_survey, name='survey_analisis'),
    url(r'^ver-tabla/(?P<id>\d+)/$', views.ver_lista, name='ver-tabla-participante'),

    url(r'^ajax/load-municipios/', views.load_municipios, name='ajax_load_municipios'),
    url(r'^ajax/load-comunidad/', views.load_comunidades, name='ajax_load_comunidad'),
    url(r'^ajax/load-caps/', views.load_caps, name='ajax_load_caps'),
]

proyecto_cfca/urls.py
# -*- coding: utf-8 -*-
"""proyecto_cfca URL Configuration

The `urlpatterns` list routes URLs to views. For more information please see:
    https://docs.djangoproject.com/en/1.11/topics/http/urls/
Examples:
Function views
    1. Add an import:  from my_app import views
    2. Add a URL to urlpatterns:  url(r'^$', views.home, name='home')
Class-based views
    1. Add an import:  from other_app.views import Home
    2. Add a URL to urlpatterns:  url(r'^$', Home.as_view(), name='home')
Including another URLconf
    1. Import the include() function: from django.conf.urls import url, include
    2. Add a URL to urlpatterns:  url(r'^blog/', include('blog.urls'))
"""
from django.conf.urls import include, url
from django.contrib import admin
from django.conf.urls.static import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.contrib.auth import views as auth_views
from proyecto_cfca import settings
#vistas
from django.views.generic import TemplateView
from aprendizaje.views import signup

admin.site.site_header = 'Administración proyecto C.F.C.A'

urlpatterns = [
    url(r'', include('web.urls')),
    url(r'^login/$', auth_views.login, name='login'),
    url(r'^signup/$', signup, name='signup'),
    url(r'^paginas/', include('django.contrib.flatpages.urls')),
    url(r'^cursos/', include('aprendizaje.urls')),
    url(r'^encuestas/', include('encuestas.urls')),
    url(r'^admin/', admin.site.urls),
    url(r'^pages/', include('django.contrib.flatpages.urls')),
    url(r'^ckeditor/', include('ckeditor_uploader.urls')),
    url(r'^taggit_autosuggest/', include('taggit_autosuggest.urls')),
    url(r'^actividades/', include('actividades.urls')),
    url(r'^censo/', include('beneficiarios.urls')),
    url(r'^caps/', include('datosCaps.urls')),
    url(r'^lugar/', include('lugar.urls')),
    url(r'^app/v1/', include('appdirectorio.urls')),
    url(r'^api-auth/', include('rest_framework.urls', namespace='rest_framework')),
    url(r'^accounts/', include('allauth.urls')),
    url(r'^redes-sociales/', include('redes_sociales.urls')),
    #url(r'^webpush/', include('webpush.urls')),
    #url(r'^sw.js', TemplateView.as_view(template_name='sw.js', content_type='application/x-javascript')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL , document_root = settings.STATIC_ROOT )
    urlpatterns += static(settings.MEDIA_URL , document_root = settings.MEDIA_ROOT )
    import debug_toolbar
    urlpatterns.append(url(r'^__debug__/', include(debug_toolbar.urls)))

urlpatterns += staticfiles_urlpatterns()

web/urls.py
from django.conf.urls import url
from django.views.generic import TemplateView
from django.views.decorators.cache import cache_page

from . import views
from beneficiarios.views import (BeneficiarioHome, 
                                BeneficiarioInversion, 
                                BeneficiarioActividad, 
                                reporte_mejoras_perforacion)
from actividadgerencial.views import ActvidadesProgramatica, ResultadosView
from modulofinanciero.views import *
from peticiones.views import *
from participantes.views import *

urlpatterns = [
    url(r'^$', views.IndexView.as_view(), name="index"),
    url(r'^search/$', views.SearchResultsView.as_view(), name='search_results'),
    url(r'^lista-noticias/$', views.NewsListView.as_view(), name="list_news"),
    url(r'^lista-noticias-vidas/$', views.NewsListVidasView.as_view(), name="list_news-vidas"),
    url(r'^noticia/(?P<slug>[-\w]+)/$', views.NewsDetailView.as_view(), name="detail_news"),
    url(r'^documentos/$', views.DocumentListView.as_view(), name="list_documents"),
    #url(r'^galerias/$', views.GaleriaListView.as_view(), name="list_gallery"),
    url(r'^galerias/$', views.GaleriaListView.as_view(), name="list_gallery"),
    url(r'^videos/$', views.VideoListView.as_view(), name="list_videos"),
    url(r'^audios/$', TemplateView.as_view(template_name="web/audios_list.html")),
    url(r'^eventos/$', views.EventosListView.as_view(), name="list_eventos"),
    url(r'^eventos/(?P<slug>[-\w]+)/$', views.EventoDetailView.as_view(), name="detail_eventos"),
    url(r'^tags/(?P<slug>[-\w]+)/$', views.TagView.as_view(), name="tags_news"),
    url(r'^tematicas/(?P<tematicas>[-\w]+)/$', views.TematicaView.as_view(), name="tematicas_news"),
    url(r'^faq/$', TemplateView.as_view(template_name="web/faq.html")),
    url(r'^consulta/$', TemplateView.as_view(template_name="seguimiento/segimiento_consulta.html")),
    url(r'^beneficiario/$', BeneficiarioHome.as_view(), name='beneficiario'),
    url(r'^beneficiario-inversion/$', BeneficiarioInversion.as_view(), name='beneficiario-inversion'),
    # url(r'^beneficiario-actividad/$', BeneficiarioActividad.as_view(), name='beneficiario-actividad'),
    url(r'^resultado/$', ResultadosView, name="resultados"),
    url(r'^impacto/$', TemplateView.as_view(template_name="seguimiento/segimiento_impacto.html")),
    url(r'^financiero/$', financiero, name='modulo_financiero'),
    url(r'^actividades/$', ActvidadesProgramatica.as_view(), name="actividades-programaticas"),
    url(r'^perfilcaps/$', TemplateView.as_view(template_name="seguimiento/perfilcaps.html")),
    url(r'^peticiones/$', peticiones, name="peticiones"),
    url(r'^peticiones/make/$', save_peticiones, name="make_peticiones"),
    url(r'^peticiones/thank/$', TemplateView.as_view(template_name="peticiones/thank.html"), name="thank_peticiones"),
    url(r'^reporte-mejoras/(?P<year>\d+)/$', reporte_mejoras_perforacion, name="reporte"),
    url(r'^covid19-nicaragua/$', TemplateView.as_view(template_name="web/covid.html")),
    url(r'^filtro-encuestas/$', consultar_survey, name="consultar-survey"),
    url(r'^salida-filtro-encuestas/$', salidas_filtro_encuesta, name="salida-consultar-survey"),

]

encuestas/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
from django.utils.encoding import python_2_unicode_compatible

from django.db import models
from django.core.exceptions import ValidationError
from datosCaps.models import FichaCaps
from lugar.models import Municipio, Comunidad

# Create your models here.
@python_2_unicode_compatible
class Survey(models.Model):
    name = models.CharField('Nombre', max_length=400)
    description = models.TextField('Descripcion')
    is_active = models.BooleanField(default=False)

    class Meta:
        verbose_name = 'Encuesta'
        verbose_name_plural = 'Encuestas'

    def __str__(self):
        return (self.name)

    def questions(self):
        if self.pk:
            return Question.objects.filter(survey=self.pk)
        else:
            return None

@python_2_unicode_compatible
class Category(models.Model):
    name = models.CharField('Nombre', max_length=400)
    #survey = models.ForeignKey(Survey)

    class Meta:
        verbose_name = 'Categoria'
        verbose_name_plural = 'Categorias'
        unique_together = ('name',)

    def __str__(self):
        return (self.name)

def validate_list(value):
    '''toma un valor de texto y verifica que haya al menos una coma '''
    values = value.split(',')
    if len(values) < 2:
        raise ValidationError("El campo seleccionado requiere una lista de opciones asociada. Las opciones deben contener más de un elemento.")

@python_2_unicode_compatible
class Question(models.Model):
    TEXT = 'text'
    RADIO = 'radio'
    SELECT = 'select'
    SELECT_MULTIPLE = 'select-multiple'
    INTEGER = 'integer'

    QUESTION_TYPES = (
        (TEXT, 'text'),
        (RADIO, 'radio'),
        (SELECT, 'select'),
        (SELECT_MULTIPLE, 'Select Multiple'),
        (INTEGER, 'integer'),
    )

    text = models.TextField('Texto')
    order = models.IntegerField("Orden")
    required = models.BooleanField('Requerido')
    category = models.ForeignKey(Category, blank=True, null=True,verbose_name='Categoria')
    survey = models.ForeignKey(Survey, verbose_name='Encuesta')
    question_type = models.CharField('Tipo de pregunta', max_length=200, choices=QUESTION_TYPES, default=TEXT)
    # el campo de opciones solo se usa si el tipo de pregunta
    choices = models.TextField(blank=True, null=True,verbose_name='Opciones',
        help_text='si el tipo de pregunta es "radio", "seleccionar" o "seleccionar múltiples", proporcione una lista de opciones separadas por comas para esta pregunta .')

    class Meta:
        verbose_name = 'Pregunta'
        verbose_name_plural = 'Preguntas'
        ordering =('order',)

    def save(self, *args, **kwargs):
        if (self.question_type == Question.RADIO or self.question_type == Question.SELECT
            or self.question_type == Question.SELECT_MULTIPLE):
            validate_list(self.choices)
        super(Question, self).save(*args, **kwargs)

    def get_choices(self):
        ''' analizar el campo de opciones y devolver una tupla formateada apropiadamente
         para el argumento 'opciones' de un widget de formulario.'''
        choices = self.choices.split(',')
        choices_list = []
        for c in choices:
            c = c.strip()
            choices_list.append((c,c))
        choices_tuple = tuple(choices_list)
        return choices_tuple

    def __str__(self):
        return (self.text)

CHOICES_SEXO = (
                (1, 'Hombre'),
                (2, 'Mujer'),
    )

CHOICES_EDAD_RANGOS = (
                (1, '16 - 22'),
                (2, '23 - 29'),
                (3, '30 - 36'),
                (4, '37 - 43'),
                (5, '44 - 49'),
                (6, '50 - 56'),
                (7, '57 en adelante'),
    )

@python_2_unicode_compatible
class Response(models.Model):
    # un objeto de respuesta es solo una colección de preguntas y respuestas con
    #una entrevista única uuid
    created = models.DateTimeField(auto_now_add=True) #volver a poner auto_now_add=True
    updated = models.DateTimeField(auto_now=True)
    survey = models.ForeignKey(Survey)
    interviewee = models.CharField('Nombre del entrevistado', max_length=400)
    interview_uuid = models.CharField("Identificador único de entrevista", max_length=36)
    municipio = models.ForeignKey(Municipio, null=True, blank=True)
    comunidad = models.ForeignKey(Comunidad,null=True, blank=True)
    caps = models.ForeignKey(FichaCaps, null=True, blank=True,
                                                    verbose_name="A que caps pertenece")
    sexo = models.IntegerField(choices=CHOICES_SEXO, null=True, blank=True)
    rango_edad = models.IntegerField(choices=CHOICES_EDAD_RANGOS, null=True, blank=True)

    class Meta:
        verbose_name = 'Respuesta'
        verbose_name_plural = 'Respuestas'

    def __str__(self):
        return ("respuesta %s" % self.interview_uuid)

class AnswerBase(models.Model):
    question = models.ForeignKey(Question)
    response = models.ForeignKey(Response)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

# estos modelos de respuestas específicas de tipo usan un campo de texto para permitir flexibilidad
# tamaños de campo dependiendo de la pregunta real a la que corresponde esta respuesta. alguna
# El atributo "requerido" será aplicado por el formulario.
class AnswerText(AnswerBase):
    body = models.TextField(blank=True, null=True)

class AnswerRadio(AnswerBase):
    body = models.TextField(blank=True, null=True)

class AnswerSelect(AnswerBase):
    body = models.TextField(blank=True, null=True)

class AnswerSelectMultiple(AnswerBase):
    body = models.TextField(blank=True, null=True)

class AnswerInteger(AnswerBase):
    body = models.IntegerField(blank=True, null=True)

templates/encuestas/analisis.html
{% extends "seguimiento/basedash.html" %}
{% block extra_css %}
    <link rel="stylesheet" href="/static/css/select2.min.css">
    <link rel="stylesheet" href="/static/bootstrap-datepicker/css/bootstrap-datepicker3.min.css">
    <link rel="stylesheet" href="/static/bootstrap-datepicker/css/bootstrap-datepicker3.standalone.min.css">
{% endblock extra_css %}
{% block contenido %}
<style>
    .select2-container .select2-selection--single{
        height: 45px;
    }
    .select2-container--default .select2-selection--single .select2-selection__rendered{
        line-height: 40px;
    }
    .user-conf{
        visibility: hidden;

    }
    .my-custom-scrollbar {
        position: relative;
        height: 400px;
        overflow: auto;
    }
    .table-wrapper-scroll-y {
        display: block;
    }
</style>
<section class="inner-header layer-overlay bg-title" data-bg-img="/static/img/imgprueba/encuesta.png">
        <div class="container pt-30 pb-30">
            <!-- Section Content -->
            <div class="section-content">
                <div class="row">
                    <div class="col-sm-8 xs-text-center">
                        <h2 class="text-white mt-10">{{survey.name|title}}</h2>
                        <ol class="breadcrumb white mt-10 text-left">
                            <li><a href="/">Inicio</a></li>
                            <li><a href="/encuestas/">Encuestas </a></li>
                            <li class="active">{{survey.name|title}}</li>
                        </ol>
                    </div>
                </div>
            </div>
        </div>
</section>
<div class="bg-silver-light">

        <section class="bg-lighter">
            <div class="container pt-20">
                <div class="row">
                    <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
                        <h4 class="title line-bottom"> Análisis <span class="text-theme-colored">Encuesta</span></h4>
                    </div>

                </div>


                <div class="row mb-20">
                    <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
                        <div class="card-admin">
                            <div class="card-body">

                                <div class="row">
                                    <h3 class="mt-0 mb-5 pr-15 pl-15">Filtros <span class="text-theme-colored"> Encuesta</span></h3>
                                        <h4 class="mt-0 mb-5 pr-15 pl-15">Número de respuestas: {{numero_respuestas}} {% if centinela %}<a href="/encuestas/ver-tabla/{{survey.id}}">(ver tabla)</a>{% endif %}</h4>
                                    <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
                                            {% include "encuestas/consulta_form.html" %}
                                    </div>

                                </div>
                            </div>


                        </div>
                    </div>
                </div>
                <div class="row mb-20">
                        <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
                            <div class="card-admin">
                                <div class="card-body mb-10">

                                    <div class="row mb-10">
                                        <h3 class="mt-0 mb-5 pr-15 pl-15">Descripción <span class="text-theme-colored"> Encuestas</span></h3>
                                        <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
                                            {{survey.description|safe}}
                                        </div>

                                    </div>
                                </div>


                            </div>
                        </div>
                    </div>

                <div class="row mb-20">
                    {% if dict_conteo_radio %}
                        {% for grafo_radio in dict_conteo_radio.items %}
                        <div class="col-xs-12 col-sm-4 col-md-4 col-lg-6 mb-20">
                            <div class="card-admin">
                                <div class="card-body">

                                    <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
                                        <div id="container-radio-{{forloop.counter}}" style="min-width: 310px; height: 400px; max-width: 600px; margin: 0 auto"></div>
                                    </div>


                                </div>


                            </div>

                        </div>
                        {% endfor %}
                    {% endif %}
                    {% if dict_conteo_select %}
                        {% for grafo_select in dict_conteo_select.items %}
                        <div class="col-xs-12 col-sm-4 col-md-4 col-lg-6 mb-20">
                            <div class="card-admin">
                                <div class="card-body">

                                    <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
                                            <div id="container-select-{{forloop.counter}}" style="min-width: 310px; height: 400px; max-width: 600px; margin: 0 auto"></div>
                                    </div>


                                </div>


                            </div>

                        </div>
                        {% endfor %}
                    {% endif %}
                    {% if dict_conteo_multiselect %}
                        {% for grafo_select in dict_conteo_multiselect.items %}
                        <div class="col-xs-12 col-sm-4 col-md-4 col-lg-6 mb-20">
                            <div class="card-admin">
                                <div class="card-body">

                                    <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
                                        <div id="container-multiselect-{{forloop.counter}}" style="min-width: 310px; height: 400px; max-width: 600px; margin: 0 auto"></div>
                                    </div>


                                </div>


                            </div>

                        </div>
                        {% endfor %}
                    {% endif %}
                    {% if dict_conteo_text %}
                        {% for k,v in dict_conteo_text.items %}
                        <div class="col-xs-12 col-sm-4 col-md-4 col-lg-6 mb-20">
                            <div class="card-admin">
                                <div class="card-body">
                                    <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
                                        <div class="table-wrapper-scroll-y my-custom-scrollbar">
                                            <table class="table table-striped table-bordered">
                                                <tr>
                                                    <td><strong>{{k}}</strong></td>
                                                </tr>
                                                {% for rps in v %}
                                                    <tr>
                                                        <td>{{rps}}</td>
                                                    </tr>
                                                {% endfor %} 
                                            </table>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                        {% endfor %}
                    {% endif %}

                </div>
            </div>

        </section>
    </div>





{% endblock contenido %}

{% block extra_js %}
<script src="https://code.jquery.com/jquery-3.1.1.min.js"></script>
<script src="https://code.highcharts.com/highcharts.js"></script>
<script src="https://code.highcharts.com/modules/exporting.js"></script>
<script src="/static/js/select2.min.js"></script>
<script src="/static/bootstrap-datepicker/js/bootstrap-datepicker.min.js"></script>
<script src="/static/bootstrap-datepicker/locales/bootstrap-datepicker.es.min.js"></script>
<script type="text/javascript">
    
$('#id_fecha_inicial').datepicker({
    format: "yyyy-mm-dd",
    language: "es",
    autoclose: true
});
$('#id_fecha_final').datepicker({
    format: "yyyy-mm-dd",
    language: "es",
    autoclose: true
});

</script>
<script type="text/javascript">
    $( "select" ).addClass( "form-control" );
    $(document).ready(function() {
        $('#id_municipio,#id_comunidad,#id_caps').select2();
    });


    $("#id_municipio").change(function () {
      var url = '/encuestas/ajax/load-comunidad/'
      var municipioId = $("#id_municipio").val();

        $.ajax({
            url: url,
            data: {
              'municipio': municipioId
            },
            success: function (data) {
              $("#id_comunidad").html(data);
            }
        });
    });

    $("#id_comunidad").change(function () {
      var url = '/encuestas/ajax/load-caps/'
      var comunidadId = $("#id_comunidad").val();

        $.ajax({
            url: url,
            data: {
              'comunidad': comunidadId
            },
            success: function (data) {
              $("#id_caps").html(data);
            }
        });
    });


</script>
{% for key, value in dict_conteo_radio.items %}
<script type="text/javascript">
// Build the chart
Highcharts.chart('container-radio-{{forloop.counter}}', {
    chart: {
        plotBackgroundColor: null,
        plotBorderWidth: null,
        plotShadow: false,
        type: 'pie'
    },
    title: {
        text: '{{key}}'
    },
    tooltip: {
        pointFormat: '{series.name}: <b>{point.percentage:.1f}%</b>'
    },
    plotOptions: {
        pie: {
            allowPointSelect: true,
            cursor: 'pointer',
            dataLabels: {
                enabled: true,
                format: '<b>{point.name}</b>: {point.percentage:.1f} %'
            },
            showInLegend: true
        }
    },
    series: [{
        name: '',
        colorByPoint: true,
        data: [
        {% for k,v in value.items %}
            {
                name: '{{k}}',
                y: {{v|default:0}}
            },
        {% endfor %}
        ]
    }]
});
</script>
{% endfor %}

{% for key, values in dict_conteo_select.items %}
<script type="text/javascript">
// Create the chart
Highcharts.chart('container-select-{{forloop.counter}}', {
    chart: {
        type: 'column'
    },
    title: {
        text: '{{key}}'
    },
    xAxis: {
        type: 'category'
    },
    yAxis: {
        title: {
            text: 'Conteo'
        }

    },
    legend: {
        enabled: false
    },
    plotOptions: {
        bar: {
            dataLabels: {
                enabled: true,
                format: '{point.y:.1f}'
            }
        }
    },
    tooltip: {
        headerFormat: '<span style="font-size:11px">{series.name}</span><br>',
        pointFormat: '<span style="color:{point.color}">{point.name}</span>: <b>{point.y:.2f}</b> of total<br/>'
    },

    series: [{
        name: '',
        colorByPoint: true,
        data: [
        {% for k,v in values.items %}
            {
                name: '{{k}}',
                y: {{v|default:0}},
            },
        {% endfor %}
        ]
    }],

});
</script>
{% endfor %}


<script type="text/javascript">
{% for key, values in dict_conteo_multiselect.items %}

var dataSum = 0;
{% for k,val in values.items %}
    dataSum += {{val}};
{% endfor %}

Highcharts.chart('container-multiselect-{{forloop.counter}}', {
    chart: {
        type: 'bar'
    },
    title: {
        text: '{{key}}'
    },
    xAxis: {
        categories: [{% for k,v in values.items %}
                        '{{k}}',
                    {% endfor %}]
    },
    yAxis: {
        min: 0,
        title: {
            text: 'Total cantidades'
        }
    },
    legend: {
        enabled: false
    },
    plotOptions: {
        series: {
            borderWidth: 0,
            dataLabels: {
                enabled: true,
                formatter:function() {
                    //var pcnt = (this.y / dataSum) * 100;
                    return  this.y;
                }
            }
        }
    },
    series: [{
        name: '',
        data: [{% for k,v in values.items %}
                    {{v}},
                {% endfor %}]
    }]
});
{% endfor %}
</script>
{% endblock extra_js %}

templates/encuestas/confirmacion.html
{% extends 'base.html' %}

{% block contenido %}

<p>Gracias! por realizar la encuestas. Su respuesta ha sido almacenada con exito!!!</p>
<a href="/encuestas/"><pre>ver mas encuestas</pre></a>

{% endblock %}

templates/encuestas/consulta_form.html
<div class="col-lg-12">
    <form action="." method="POST" autocomplete="off">{% csrf_token %}
		<div class="row">

			<div class="col-xs-12 col-sm-12 col-md-4 col-lg-4">
				<div class="form-group">
					<label for="sexo">Fecha inicial</label>
					{{form.fecha_inicial}}
				</div>
			</div>
			<div class="col-xs-12 col-sm-12 col-md-4 col-lg-4">
				<div class="form-group">
					<label for="sexo">Fecha final</label>
					{{form.fecha_final}}
				</div>
			</div>
			
			<div class="col-xs-12 col-sm-12 col-md-4 col-lg-4">
				<div class="form-group">
					<label for="sexo">Sexo</label>
					{{form.sexo}}
				</div>
			</div>
			<div class="col-xs-12 col-sm-12 col-md-4 col-lg-4">
				<div class="form-group">
					<label for="rango_edad">Rango de edad</label>
					{{form.rango_edad}}
				</div>
			</div>
			<div class="col-xs-12 col-sm-12 col-md-4 col-lg-4">
				<div class="form-group">
					<label for="municipio">Municipio</label>
					{{form.municipio}}
				</div>
			</div>
			<div class="col-xs-12 col-sm-12 col-md-4 col-lg-4">
				<div class="form-group">
					<label for="comunidad">Comunidad</label>
					{{form.comunidad}}
				</div>
			</div>
			<div class="col-xs-12 col-sm-12 col-md-4 col-lg-4">
				<div class="form-group">
					<label for="caps">Caps</label>
					{{form.caps}}
				</div>
			</div>
		</div>
        <div class="">
            <input type="submit" value="Consultar" id="boton" class="btn btn-success"/>
        </div>
    </form>
</div>

templates/encuestas/encuesta.html
{% extends 'base.html' %}
{% load survey_extras %}
{% block extra_css %}
    <link href="/static/css/radio.css" rel="stylesheet" type="text/css">
    <link rel="stylesheet" href="/static/css/select2.min.css">
{% endblock extra_css %}
{% block contenido %}
<style>
.select2-container .select2-selection--single{
    height: 45px;
}
.select2-container--default .select2-selection--single .select2-selection__rendered{
    line-height: 40px;
}
form label {
    font-size: 25px;
}
.agrandar {
    font-size: 30px;
}
</style>

<section class="inner-header layer-overlay bg-title" data-bg-img="/static/img/imgprueba/encuesta.png">
        <div class="container pt-30 pb-30">
            <!-- Section Content -->
            <div class="section-content">
                <div class="row">
                    <div class="col-sm-8 xs-text-center">
                        <h2 class="text-white mt-10">{{survey.name|title}}</h2>
                        <ol class="breadcrumb white mt-10 text-left">
                            <li><a href="/">Inicio</a></li>
                            <li><a href="/encuestas/">Encuestas </a></li>
                            <li class="active">{{survey.name|title}}</li>
                        </ol>
                    </div>
                </div>
            </div>
        </div>
</section>
<section>
    <div class="container">
        <div class="row">

            <div class="col-md-12">
                <div class="survey-description">
                    <h3>Descripción</h3>
                    <hr>
                    {{survey.description|safe}}
                </div>
                <form action="/encuestas/survey/{{survey.id}}/" method="post">{% csrf_token %}
                    <ol class="survey-questions">
                        <div class="category-container">
                            {% for field in response_form %}
                                <li id="section-one" class="mb-50 q-item" value="{% counter %}">
                                    {% if field.field.required %}
                                        <div class="field-wrapper question-required">
                                            {{ field.errors }}

                                            <label class="label-inline">
                                                <h3 class="mb-0">{{ field.label }}</h3>
                                            </label>
                                            <span class="asterix"> <span class="label label-danger">Requerido*</span> </span>
                                            <hr class="mt-0">
                                        {% else %}
                                        <div class="field-wrapper">
                                            {{ field.errors }}
                                            <label class="label-inline agrandar">
                                                <h3 class="mb-0">{{ field.label }}</h3>
                                            </label>
                                            <hr class="mt-0">
                                        {% endif %}
                                            <span class="form-help-text">{{ field.help_text}}</span>
                                            <div class="form-field-body">
                                                {{ field }}
                                            </div>
                                        </div>
                                </li>
                            {% endfor %}
                        </div>
                    </ol>
                    <div ><input type="submit" class="btn btn-success" value="enviar"></div>
                </form>
            </div>
        </div>
    </div>
</section>



{% endblock %}

{% block extra_js %}
    <script src="/static/js/select2.min.js"></script>
    <script type="text/javascript">
        $( "input[type='text'],input[type='number'], select, textarea" ).addClass( "form-control" );
        $( "input[type='radio']" ).addClass( "radio" );
        $(document).ready(function() {
            $('#id_municipio,#id_comunidad,#id_caps').select2();
        });

    $("#id_municipio").change(function () {
      var url = '/encuestas/ajax/load-comunidad/'
      var municipioId = $("#id_municipio").val();

        $.ajax({
            url: url,
            data: {
              'municipio': municipioId
            },
            success: function (data) {
              $("#id_comunidad").html(data);
            }
        });
    });

    $("#id_comunidad").change(function () {
      var url = '/encuestas/ajax/load-caps/'
      var municipioId = $("#id_comunidad").val();

        $.ajax({
            url: url,
            data: {
              'comunidad': municipioId
            },
            success: function (data) {
              $("#id_caps").html(data);
            }
        });
    });

    </script>
{% endblock %}