proyecto_cfca/urls.py
# -*- coding: utf-8 -*-
"""proyecto_cfca URL Configuration

The `urlpatterns` list routes URLs to views. For more information please see:
    https://docs.djangoproject.com/en/1.11/topics/http/urls/
Examples:
Function views
    1. Add an import:  from my_app import views
    2. Add a URL to urlpatterns:  url(r'^$', views.home, name='home')
Class-based views
    1. Add an import:  from other_app.views import Home
    2. Add a URL to urlpatterns:  url(r'^$', Home.as_view(), name='home')
Including another URLconf
    1. Import the include() function: from django.conf.urls import url, include
    2. Add a URL to urlpatterns:  url(r'^blog/', include('blog.urls'))
"""
from django.conf.urls import include, url
from django.contrib import admin
from django.conf.urls.static import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.contrib.auth import views as auth_views
from proyecto_cfca import settings
#vistas
from django.views.generic import TemplateView
from aprendizaje.views import signup

admin.site.site_header = 'Administración proyecto C.F.C.A'

urlpatterns = [
    url(r'', include('web.urls')),
    url(r'^login/$', auth_views.login, name='login'),
    url(r'^signup/$', signup, name='signup'),
    url(r'^paginas/', include('django.contrib.flatpages.urls')),
    url(r'^cursos/', include('aprendizaje.urls')),
    url(r'^encuestas/', include('encuestas.urls')),
    url(r'^admin/', admin.site.urls),
    url(r'^pages/', include('django.contrib.flatpages.urls')),
    url(r'^ckeditor/', include('ckeditor_uploader.urls')),
    url(r'^taggit_autosuggest/', include('taggit_autosuggest.urls')),
    url(r'^actividades/', include('actividades.urls')),
    url(r'^censo/', include('beneficiarios.urls')),
    url(r'^caps/', include('datosCaps.urls')),
    url(r'^lugar/', include('lugar.urls')),
    url(r'^app/v1/', include('appdirectorio.urls')),
    url(r'^api-auth/', include('rest_framework.urls', namespace='rest_framework')),
    url(r'^accounts/', include('allauth.urls')),
    url(r'^redes-sociales/', include('redes_sociales.urls')),
    #url(r'^webpush/', include('webpush.urls')),
    #url(r'^sw.js', TemplateView.as_view(template_name='sw.js', content_type='application/x-javascript')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL , document_root = settings.STATIC_ROOT )
    urlpatterns += static(settings.MEDIA_URL , document_root = settings.MEDIA_ROOT )
    import debug_toolbar
    urlpatterns.append(url(r'^__debug__/', include(debug_toolbar.urls)))

urlpatterns += staticfiles_urlpatterns()

web/urls.py
from django.conf.urls import url
from django.views.generic import TemplateView
from django.views.decorators.cache import cache_page

from . import views
from beneficiarios.views import (BeneficiarioHome, 
                                BeneficiarioInversion, 
                                BeneficiarioActividad, 
                                reporte_mejoras_perforacion)
from actividadgerencial.views import ActvidadesProgramatica, ResultadosView
from modulofinanciero.views import *
from peticiones.views import *
from participantes.views import *

urlpatterns = [
    url(r'^$', views.IndexView.as_view(), name="index"),
    url(r'^search/$', views.SearchResultsView.as_view(), name='search_results'),
    url(r'^lista-noticias/$', views.NewsListView.as_view(), name="list_news"),
    url(r'^lista-noticias-vidas/$', views.NewsListVidasView.as_view(), name="list_news-vidas"),
    url(r'^noticia/(?P<slug>[-\w]+)/$', views.NewsDetailView.as_view(), name="detail_news"),
    url(r'^documentos/$', views.DocumentListView.as_view(), name="list_documents"),
    #url(r'^galerias/$', views.GaleriaListView.as_view(), name="list_gallery"),
    url(r'^galerias/$', views.GaleriaListView.as_view(), name="list_gallery"),
    url(r'^videos/$', views.VideoListView.as_view(), name="list_videos"),
    url(r'^audios/$', TemplateView.as_view(template_name="web/audios_list.html")),
    url(r'^eventos/$', views.EventosListView.as_view(), name="list_eventos"),
    url(r'^eventos/(?P<slug>[-\w]+)/$', views.EventoDetailView.as_view(), name="detail_eventos"),
    url(r'^tags/(?P<slug>[-\w]+)/$', views.TagView.as_view(), name="tags_news"),
    url(r'^tematicas/(?P<tematicas>[-\w]+)/$', views.TematicaView.as_view(), name="tematicas_news"),
    url(r'^faq/$', TemplateView.as_view(template_name="web/faq.html")),
    url(r'^consulta/$', TemplateView.as_view(template_name="seguimiento/segimiento_consulta.html")),
    url(r'^beneficiario/$', BeneficiarioHome.as_view(), name='beneficiario'),
    url(r'^beneficiario-inversion/$', BeneficiarioInversion.as_view(), name='beneficiario-inversion'),
    # url(r'^beneficiario-actividad/$', BeneficiarioActividad.as_view(), name='beneficiario-actividad'),
    url(r'^resultado/$', ResultadosView, name="resultados"),
    url(r'^impacto/$', TemplateView.as_view(template_name="seguimiento/segimiento_impacto.html")),
    url(r'^financiero/$', financiero, name='modulo_financiero'),
    url(r'^actividades/$', ActvidadesProgramatica.as_view(), name="actividades-programaticas"),
    url(r'^perfilcaps/$', TemplateView.as_view(template_name="seguimiento/perfilcaps.html")),
    url(r'^peticiones/$', peticiones, name="peticiones"),
    url(r'^peticiones/make/$', save_peticiones, name="make_peticiones"),
    url(r'^peticiones/thank/$', TemplateView.as_view(template_name="peticiones/thank.html"), name="thank_peticiones"),
    url(r'^reporte-mejoras/(?P<year>\d+)/$', reporte_mejoras_perforacion, name="reporte"),
    url(r'^covid19-nicaragua/$', TemplateView.as_view(template_name="web/covid.html")),
    url(r'^filtro-encuestas/$', consultar_survey, name="consultar-survey"),
    url(r'^salida-filtro-encuestas/$', salidas_filtro_encuesta, name="salida-consultar-survey"),

]

web/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
from django.utils.encoding import python_2_unicode_compatible

from django.db import models
from django.contrib.auth.models import User
from django.template.defaultfilters import slugify
from django.urls import reverse
from django.contrib.contenttypes.fields import GenericForeignKey, GenericRelation
from django.contrib.contenttypes.models import ContentType
from django.db.models.signals import post_save
from django.dispatch import receiver

from sorl.thumbnail import ImageField
from taggit_autosuggest.managers import TaggableManager
from location_field.models.plain import PlainLocationField

from lugar.models import Departamento, Municipio
from newsletters.models import CorreoEnvioNotificacion
from django.core.mail import send_mail
from django.template.loader import render_to_string
from django.contrib.sites.models import Site

# Create your models here.
@python_2_unicode_compatible
class Tematicas(models.Model):
    nombre = models.CharField(max_length=250)
    slug = models.SlugField(max_length=250, editable=False)
    color = models.CharField(max_length=150, null=True, blank=True)

    def __str__(self):
        return self.nombre

    def save(self, *args, **kwargs):
        self.slug = (slugify(self.nombre))
        super(Tematicas, self).save(*args, **kwargs)

    class Meta:
        verbose_name = 'Tematica'
        verbose_name_plural = 'Tematicas'

@python_2_unicode_compatible
class ArchivosAdjuntos(models.Model):
    nombre = models.CharField(max_length=250)
    credito = models.CharField(max_length=250)
    archivo = models.FileField(upload_to='adjuntos/')
    content_type = models.ForeignKey(ContentType, on_delete=models.CASCADE)
    object_id = models.PositiveIntegerField()
    content_object = GenericForeignKey('content_type', 'object_id')

    def __str__(self):
        return self.nombre

    class Meta:
        verbose_name = 'Archivos adjunto'
        verbose_name_plural = 'Archivos adjuntos'

@python_2_unicode_compatible
class GaleriasFotos(models.Model):
    titulo = models.CharField(max_length=250)
    slug = models.SlugField(max_length=250, editable=False)
    fecha = models.DateTimeField('Fecha', auto_now=True)
    credito = models.CharField(max_length=250)
    tematicas = models.ManyToManyField(Tematicas, blank=True)
    archivo = ImageField(upload_to='galeria/')
    infografia_mostrar = models.BooleanField(default=False)
    content_type = models.ForeignKey(ContentType, on_delete=models.CASCADE)
    object_id = models.PositiveIntegerField()
    content_object = GenericForeignKey('content_type', 'object_id')

    def __str__(self):
        return self.titulo

    def save(self, *args, **kwargs):
        self.slug = (slugify(self.titulo))
        super(GaleriasFotos, self).save(*args, **kwargs)

    class Meta:
        verbose_name = 'Galeria de foto'
        verbose_name_plural = 'Galerias de fotos'

    @models.permalink
    def get_absolute_url(self):
        return ("galeria-detalle", [self.slug,])

CHOICE_TIPO_NOTICIA = ((1,'Infórmate'),(2,'Vida de CAPS'),)
CHOICE_PERMISO_PUBLICACION = ((1,'Publicada'),(2,'En desarrollo'),)

@python_2_unicode_compatible
class Noticias(models.Model):
    titulo = models.CharField(max_length=250)
    slug = models.SlugField(max_length=250, editable=False)
    fecha_publicacion = models.DateTimeField('Fecha de publicación')
    en_portada = models.BooleanField(default=False)
    permanente_en_inicio = models.BooleanField(default=False)
    foto_principal = ImageField(upload_to='foto/noticias/', null=True, blank=True)
    descripcion_foto = models.CharField(max_length=150, null=True, blank=True)
    video_principal = models.URLField(null=True, blank=True)
    credito_foto = models.CharField(max_length=250, null=True, blank=True)
    texto_noticia = models.TextField('Texto de la noticia')
    autor_noticia = models.ForeignKey(User, verbose_name='Autor de la noticia')
    seccion = models.IntegerField(choices=CHOICE_TIPO_NOTICIA)
    tematicas = models.ManyToManyField(Tematicas)
    tags = TaggableManager('palabras_claves')
    adjuntar = GenericRelation(ArchivosAdjuntos)
    galeria = GenericRelation(GaleriasFotos)
    publicar = models.IntegerField(choices=CHOICE_PERMISO_PUBLICACION)
    enviar_notificacion = models.BooleanField(default=False)

    def __str__(self):
        return self.titulo

    def save(self, *args, **kwargs):
        self.slug = (slugify(self.titulo))
        super(Noticias, self).save(*args, **kwargs)

    class Meta:
        verbose_name = 'Noticia'
        verbose_name_plural = 'Noticias'


    def get_absolute_url(self):
        from django.urls import reverse
        return reverse('detail_news', args=[str(self.slug)])
        #return ("detail_news", [self.slug,])

    def get_tematica(self):
        tema = self.tematicas.all()[0].nombre
        return tema

    def get_tematica_color(self):
        tema = self.tematicas.all()[0].color
        return tema

    def todas_tematicas(self):
        all_temas = ','.join([obj.nombre for obj in self.tematicas.all()])
        return all_temas

@receiver(post_save, sender=Noticias)
def send_new_message_notification(sender, created, **kwargs):
    message = kwargs['instance']
    obj = User.objects.get(pk=message.autor_noticia.pk)
    if message.publicar == 1 and message.enviar_notificacion == True:
        #print("enviar mensaje por correo!")
        site = Site.objects.get_current()
        contenido = render_to_string('web/notify_new_nota.txt', {'nota': message,
                                     'url': '%s/noticia/%s' % (site, message.slug),
                                     })
        send_mail('Noticias CAPS Nicaragua', contenido, 'proyecto.cfca@gmail.com', 
            [user.correo_electronico for user in CorreoEnvioNotificacion.objects.all() if user.correo_electronico])
   

@python_2_unicode_compatible
class VoceDelAgua(models.Model):
    titulo = models.CharField('Autor', max_length=250)
    fecha = models.DateTimeField(auto_now=True)
    foto_principal = ImageField(upload_to='foto/voces_del_agua/', null=True, blank=True)
    credito_foto = models.CharField('lugar', max_length=250, null=True, blank=True)
    descripcion = models.TextField('Descripción')

    def __str__(self):
        return self.titulo

    class Meta:
        verbose_name = 'Voces del agua'
        verbose_name_plural = 'Voces del agua'

    @models.permalink
    def get_absolute_url(self):
        return reverse('vocesdelagua-detalle', args=[str(self.id)])

CHOICE_TIPO_PUBLICACION = ((1,'Revista'),(2,'Manual'),(3,'Investigación'),(4,'Informe'),)

@python_2_unicode_compatible
class Publicaciones(models.Model):
    titulo = models.CharField(max_length=250)
    slug = models.SlugField(max_length=250, editable=False)
    fecha = models.DateTimeField(auto_now=True)
    imagen_portada = ImageField(upload_to='foto/publicaciones/', null=True, blank=True)
    autor = models.CharField(verbose_name='Autor de la publicación', max_length=250)
    lugar = models.CharField(max_length=250, null=True, blank=True)
    descripcion = models.TextField('Descripción')
    tematicas = models.ManyToManyField(Tematicas)
    palabras_claves = TaggableManager()
    edicion = models.CharField('Edición', max_length=50)
    tipo_publicacion = models.IntegerField(choices=CHOICE_TIPO_PUBLICACION, verbose_name='Tipo de publicación')
    adjuntar = GenericRelation(ArchivosAdjuntos)

    def __str__(self):
        return self.titulo

    def save(self, *args, **kwargs):
        self.slug = (slugify(self.titulo))
        super(Publicaciones, self).save(*args, **kwargs)

    class Meta:
        verbose_name = 'Publicación'
        verbose_name_plural = 'Publicaciones'

    @models.permalink
    def get_absolute_url(self):
        return ("publicacion-detalle", [self.slug,])

    def todas_tematicas(self):
        all_temas = ', '.join([obj.nombre for obj in self.tematicas.all()])
        return all_temas

    def all_tematicas(self):
        all_temas = ' '.join([slugify(obj.nombre) for obj in self.tematicas.all()])
        return all_temas

class ListasVideos(models.Model):
    nombre = models.CharField(max_length=250)

    def __str__(self):
        return self.nombre

    class Meta:
        verbose_name_plural = "Listas para los videos"


@python_2_unicode_compatible
class Videos(models.Model):
    titulo = models.CharField(max_length=250)
    lista_categoria = models.ForeignKey(ListasVideos, null=True, blank=True)
    slug = models.SlugField(max_length=250, editable=False)
    fecha = models.DateTimeField(auto_now=True)
    imagen_portada = ImageField(upload_to='foto/videos/', null=True, blank=True)
    video_url = models.URLField()
    descripcion = models.TextField('Descripción')
    tematicas = models.ManyToManyField(Tematicas)
    palabras_claves = TaggableManager()

    def __str__(self):
        return self.titulo

    def save(self, *args, **kwargs):
        self.slug = (slugify(self.titulo))
        super(Videos, self).save(*args, **kwargs)

    class Meta:
        verbose_name = 'Video'
        verbose_name_plural = 'Videos'

    @models.permalink
    def get_absolute_url(self):
        return ("video-detalle", [self.slug,])


@python_2_unicode_compatible
class Eventos(models.Model):
    titulo = models.CharField(max_length=250)
    slug = models.SlugField(max_length=250, editable=False)
    fecha = models.DateTimeField()
    imagen_portada = ImageField(upload_to='foto/eventos/', null=True, blank=True)
    autor = models.ForeignKey(User, verbose_name='Autor de la publicación')
    lugar = models.CharField(max_length=250, null=True, blank=True)
    departamento = models.ForeignKey(Departamento, null=True)
    municipio = models.ForeignKey(Municipio, null=True)
    descripcion = models.TextField('Descripción')
    tematicas = models.ManyToManyField(Tematicas)
    nombre_contacto = models.CharField('Nombre del contacto',max_length=250)

templates/web/audios_list.html
{% extends "base.html" %}
{% block extra_css %}
	<link href="/static/css/audio.css" rel="stylesheet" type="text/css">
{% endblock extra_css %}
{% block contenido %}
<div class="audio-player-container"></div>
{% endblock contenido %}
{% block extra_js %}
	<script src="/static/js/audio.js" type="text/javascript"></script>
{% endblock extra_js %}

templates/web/documentos_list.html
{% extends "base.html" %}

{% load thumbnail %}
{% load solo_tags %}

{% block extra_css %}
<link href="/static/css/hover/imagehover.min.css" rel="stylesheet" type="text/css">
{% endblock extra_css %}

{% block extra_js %}
<script src="/static/js/filter/filter.js"></script>
<script>
    $('.menuzord-menu li.dm-doc').addClass('active');
</script>
{% endblock extra_js %}

{% block contenido %}
{% get_solo 'configuracion.SiteConfiguration' as site_config %}
<section class="inner-header layer-overlay bg-title"
    {% thumbnail site_config.foto_fondo_documentos '1300x200' as im %}data-bg-img="{{im.url}}" {% endthumbnail %}>
    <div class="container pt-30 pb-30">
        <!-- Section Content -->
        <div class="section-content">
            <div class="row">
                <div class="col-sm-8 xs-text-center">
                    <h2 class="text-white mt-10">Documentos</h2>
                    <ol class="breadcrumb white mt-10 text-left">
                        <li><a href="/">Inicio</a></li>
                        <li class="active">Documéntate</li>
                    </ol>
                </div>
            </div>
        </div>
    </div>
</section>
<!-- Section: aprende  -->
<section>
    <div class="container">
        <div class="row mb-20">
            <h4>Temas:</h4>
            <div role="tabpanel">
                <ul class="nav nav-filter" role="tablist">
                    <li role="presentation" class="active">
                        <a class="btn btn-default filter-button mb-10" href="#" aria-controls="home" role="tab" data-toggle="tab" data-filter="all">Todos</a>
                    </li>
                    {% for obj in tematica %}
                    <li role="presentation">
                        <a class="btn btn-default filter-button mb-10" href="#" aria-controls="tab" role="tab" data-toggle="tab" data-filter="{{obj.slug}}">{{obj}}</a>
                    </li>
                    {% endfor %}
                </ul>

            </div>
        </div>
        <div class="row multi-row-clearfix">
            <div class="blog-posts">
                {% for obj in object_list %}
                <div class="col-md-3 filter all {{obj.all_tematicas|lower}}">
                    <article class="post clearfix mb-30 bg-lighter">
                        <div class="entry-header">
                            <a data-toggle="modal" href="#documento-{{obj.id}}" class="post-thumb thumb">
                                <figure class="post-thumb thumb imghvr-zoom-out bg-theme-colored">
                                    {% if obj.imagen_portada %}
                                    {% thumbnail obj.imagen_portada "595x842" crop='center' as im %}
                                    <img src="{{ im.url }}" alt="{{obj.titulo}}" class="img-responsive img-fullwidth">
                                    {% endthumbnail %}
                                    {% else %}
                                    <img src="http://placehold.it/595x842" alt="obj.titulo"
                                        class="img-responsive img-fullwidth">
                                    {% endif %}

                                    <figcaption class="bg-theme-colored">
                                        <p>{{obj.descripcion|safe|truncatewords:40|striptags}}</p>
                                    </figcaption>
                                </figure>
                            </a>
                        </div>
                        <div class="entry-content p-10 pr-10">
                            <div class="entry-meta media mt-0 no-bg no-border">

                                <div class="media-body">
                                    <div class="event-content pull-left flip">
                                        <h5 class="entry-title text-white text-uppercase mb-15 mt-5"><a
                                                data-toggle="modal" href="#documento-{{obj.id}}">{{obj.titulo}}</a></h5>

                                    </div>
                                </div>
                            </div>

                            {% if obj.adjuntar.all|length > 1 %}
                            <div class="btn-group">
                                <button type="button" class="btn btn-primary btn-theme-colored">Descargar Archivos</button>
                                <button type="button" class="btn btn-primary dropdown-toggle btn-theme-colored"
                                    data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                    <span class="caret"></span>
                                    <span class="sr-only">Toggle Dropdown</span>
                                </button>
                                <ul class="dropdown-menu">
                                    {% for attach in obj.adjuntar.all %}
                                    <li><a target="_blank" href="/media/{{attach.archivo}}">{{attach.nombre}}</a></li>
                                    {% if forloop.last %}

                                    {% else %}
                                    <li role="separator" class="divider"></li>
                                    {% endif %}

                                    {% endfor %}
                                </ul>
                            </div>
                            {% else %}
                                {% for attach in obj.adjuntar.all %}
                                    <a target="_blank" href="/media/{{attach.archivo}}" class="btn btn-primary btn-theme-colored">Descargar Archivo</a>
                                {% endfor %}
                            {% endif %}






                            <div class="clearfix"></div>
                        </div>
                        <div class="modal vd-modal" id="documento-{{obj.id}}" data-easein="expandIn">
                            <div class="modal-dialog modal-lg">
                                <div class="modal-content">
                                    <div class="modal-header">
                                        <button type="button" class="close" data-dismiss="modal"
                                            aria-hidden="true">&times;</button>
                                        <h4 class="modal-title"></h4>
                                    </div>

                                    <div class="modal-body">
                                        <div class="row">
                                            <div class="col-xm-12 col-md-6">
                                                <figure class="post-thumb thumb">
                                                    {% if obj.imagen_portada %}
                                                    {% thumbnail obj.imagen_portada "595x842" crop='center' as im %}
                                                    <img src="{{ im.url }}" alt="{{obj.titulo}}"
                                                        class="img-responsive img-fullwidth">
                                                    {% endthumbnail %}
                                                    {% else %}
                                                    <img src="http://placehold.it/595x842" alt="{{obj.titulo}}"
                                                        class="img-responsive img-fullwidth">
                                                    {% endif %}

                                                </figure>
                                            </div>
                                            <div class="col-xm-12 col-md-6">
                                                <div class="product-summary">
                                                    <h3 class="product-title font-weight-600 line-bottom">{{obj.titulo}}
                                                    </h3>
                                                    <div class="autor pt-5 pb-5">
                                                        <strong class="text-theme-colored"><i class="fa fa-user"></i>
                                                            Autor: </strong>{{obj.autor}}
                                                    </div>
                                                    <div class="autor pt-5 pb-5">
                                                        <strong class="text-theme-colored"><i
                                                                class="fa fa-map-marker"></i> Lugar:
                                                        </strong>{{obj.lugar}}
                                                    </div>

                                                    <div class="short-description pt-5 pb-5">
                                                        <strong class="text-theme-colored"> Descripción:</strong>
                                                        <p>{{obj.descripcion|safe}}.</p>
                                                    </div>

                                                    <div class="tematica pt-5 pb-5"><strong class="text-theme-colored">
                                                            Temática:</strong>
                                                        <a href="#">{{obj.todas_tematicas|lower}}</a>
                                                    </div>
                                                    <div class="tags pt-5 pb-5"><strong class="text-theme-colored"><i
                                                                class="fas fa-tags"></i> Tags:</strong>
                                                        {% for obj in  obj.palabras_claves.all %}
                                                        <a href="#">{{obj}}</a>,
                                                        {% endfor %}
                                                    </div>
                                                    <div class="edicion pt-5 pb-5"><strong class="text-theme-colored"><i
                                                                class="fas fa-book"></i> Edición:</strong>
                                                        {{obj.edicion}}
                                                    </div>
                                                    <div class="tipo pt-5 pb-5"><strong
                                                            class="text-theme-colored">Tipo:</strong>
                                                        <a href="#">{{obj.get_tipo_publicacion_display}}</a>
                                                        <div class="edicion pt-5 pb-5"><strong>Descargar archivos
                                                                adjuntos:</strong></div>
                                                        <div class="cart-form-wrapper">
                                                            {% for attach in obj.adjuntar.all %}
                                                            <a href="/media/{{attach.archivo}}"
                                                                class="single_add_to_cart_button btn btn-theme-colored"
                                                                type="submit">{{attach.nombre}} <i
                                                                    class="fa fa-download"></i></a>
                                                            {% endfor %}

                                                        </div>
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                    </article>
                </div>
                {% endfor %}

                <div class="col-md-12">
                    <nav>
                        {% if is_paginated %}
                        <ul class="pagination theme-colored">
                            {% if page_obj.has_previous %}
                            <li><a href="?page={{ page_obj.previous_page_number }}">&laquo;</a></li>
                            {% else %}
                            <li class="disabled"><span>&laquo;</span></li>
                            {% endif %}
                            {% for i in paginator.page_range %}
                            {% if page_obj.number == i %}
                            <li class="active"><span>{{ i }} <span class="sr-only">(current)</span></span></li>
                            {% else %}
                            <li><a href="?page={{ i }}">{{ i }}</a></li>
                            {% endif %}
                            {% endfor %}
                            {% if page_obj.has_next %}
                            <li><a href="?page={{ page_obj.next_page_number }}">&raquo;</a></li>
                            {% else %}
                            <li class="disabled"><span>&raquo;</span></li>
                            {% endif %}
                        </ul>
                        {% endif %}
                    </nav>
                </div>
            </div>
        </div>
    </div>
</section>

{% endblock contenido %}